# Generated by Django 3.2.8 on 2021-11-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_user_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_id',
            new_name='saldo',
        ),
    ]
