# Generated by Django 3.2.8 on 2021-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_customer_id_user_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='juegosComprados',
            field=models.ManyToManyField(to='tienda.Videojuego'),
        ),
    ]
