# Generated by Django 3.2.8 on 2021-11-17 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_user_juegoscomprados'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amigos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tienda_user_amigos_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
