# Generated by Django 3.2.8 on 2021-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_user_amigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='juegosComprados',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.Videojuego'),
        ),
    ]
