# Generated by Django 3.2.8 on 2021-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_videojuego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
