# Generated by Django 3.2.8 on 2021-11-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_user_saldo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraVideojuego',
        ),
    ]
