# Generated by Django 3.2.8 on 2021-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_delete_compravideojuego'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='images/logos')),
            ],
        ),
        migrations.CreateModel(
            name='VideoVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='videos/juegos')),
            ],
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='imagen',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.VideoVideojuego'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.ImagenVideojuego'),
        ),
    ]
