# Generated by Django 3.2.8 on 2021-11-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_auto_20211124_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoVideojuego',
        ),
    ]
