# Generated by Django 3.2.8 on 2021-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_auto_20211124_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('video', models.FileField(blank=True, upload_to='videos/juegos')),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.VideoVideojuego'),
        ),
    ]
