# Generated by Django 3.2.8 on 2021-11-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_auto_20211124_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='video',
        ),
        migrations.DeleteModel(
            name='ImagenVideojuego',
        ),
        migrations.DeleteModel(
            name='VideoVideojuego',
        ),
    ]
