# Generated by Django 3.2.8 on 2021-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_auto_20211124_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenVideojuego',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='images/logos')),
            ],
        ),
        migrations.CreateModel(
            name='VideoVideojuego',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, upload_to='videos/juegos')),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.ImagenVideojuego'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='tienda.VideoVideojuego'),
        ),
    ]
