# Generated by Django 3.2.8 on 2021-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_auto_20211124_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaRegalo',
            fields=[
                ('saldo', models.DecimalField(decimal_places=2, max_digits=100, max_length=5)),
                ('codigo', models.CharField(max_length=10000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='imagenvideojuego',
            name='imagen',
            field=models.FileField(blank=True, upload_to='images/logos'),
        ),
    ]
