# Generated by Django 3.2.8 on 2021-12-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_tarjetaregalo_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetaregalo',
            name='habilitado',
            field=models.BooleanField(),
        ),
    ]
